name: 🐛 Raise a bug
description: |
  This template is used to create a new bug report.
  Please provide as much information as possible.
labels:
  - 'bug'
title: '🐛 New Bug:'
body:
  - type: input
    id: description
    attributes:
      label: ❓ What is the bug?
      placeholder: Briefly describe the bug you are reporting
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Affected Version
      description: 🔢 What version of the reporter is this bug related to?
      placeholder: Affected version
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 📃 Steps to reproduce the bug
      description: We highly suggest including a screenshots and a bug report log (GitHub Gist link).
      placeholder: Tell us the steps required to replicate your bug.
    validations:
      required: true

  - type: textarea
    id: expected-result
    attributes:
      label: ✅ Expected Behavior
      placeholder: What were you expecting?
      description: Describe the expected behavior you were expecting.
    validations:
      required: true

  - type: textarea
    id: actual-result
    attributes:
      label: ❌ Actual Behavior
      placeholder: What actually happened?
      description: Describe the actual behavior that you noticed.
    validations:
      required: true
